
export const Routes = {
    // pages
    Presentation: { path: "/library" },
    DashboardOverview: { path: "/library/dashboard/overview" },
    Transactions: { path: "/library/transactions" },
    Settings: { path: "/library/settings" },
    Upgrade: { path: "/library/upgrade" },
    BootstrapTables: { path: "/library/tables/bootstrap-tables" },
    Billing: { path: "/library/examples/billing" },
    Invoice: { path: "/library/examples/invoice" },
    Signin: { path: "/library/examples/sign-in" },
    Signup: { path: "/library/examples/sign-up" },
    ForgotPassword: { path: "/library/examples/forgot-password" },
    ResetPassword: { path: "/library/examples/reset-password" },
    Lock: { path: "/library/examples/lock" },
    NotFound: { path: "/library/examples/404" },
    ServerError: { path: "/library/examples/500" },

    // docs
    DocsOverview: { path: "/library/documentation/overview" },
    DocsDownload: { path: "/library/documentation/download" },
    DocsQuickStart: { path: "/library/documentation/quick-start" },
    DocsLicense: { path: "/library/documentation/license" },
    DocsFolderStructure: { path: "/library/documentation/folder-structure" },
    DocsBuild: { path: "/library/documentation/build-tools" },
    DocsChangelog: { path: "/library/documentation/changelog" },

    // components
    Accordions: { path: "/library/components/accordions" },
    Alerts: { path: "/library/components/alerts" },
    Badges: { path: "/library/components/badges" },
    Widgets: { path: "/library/widgets" },
    Breadcrumbs: { path: "/library/components/breadcrumbs" },
    Buttons: { path: "/library/components/buttons" },
    Forms: { path: "/library/components/forms" },
    Modals: { path: "/library/components/modals" },
    Navs: { path: "/library/components/navs" },
    Navbars: { path: "/library/components/navbars" },
    Pagination: { path: "/library/components/pagination" },
    Popovers: { path: "/library/components/popovers" },
    Progress: { path: "/library/components/progress" },
    Tables: { path: "/library/components/tables" },
    Tabs: { path: "/library/components/tabs" },
    Tooltips: { path: "/library/components/tooltips" },
    Toasts: { path: "/library/components/toasts" },
    WidgetsComponent: { path: "/library/components/widgets" },

    // foreignWorker
    ForeignWorker: { path: "/" },
    ForeignWorkerEmployee: { path: "/employees" },
    ForeignWorkerPayroll: { path: "/payroll/run" },
    ForeignWorkerPayrollHistory: { path: "/payroll/history" },
    ForeignWorkerPayrollHistoryDetail: { path: "/payroll/history/view/:id" },
    ForeignWorkerReminder: { path: "/reminder" },
    ForeignWorkerLinks: { path: "/links" },
    ForeignWorkerSetting: { path: "/setting" },
    ForeignWorkerProfile: { path: "/profile" },
    ForeignWorkerLogin: { path: "/login" },
    ForeignWorkerRegister: { path: "/register" },
    ForeignWorkerNotFound: { path: "/404" },
};